services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/app-data:/srv/app-data
      - ${ROOT_FOLDER_HOST}/media:/srv/media
      - ${APP_DATA_DIR}/data/general:/srv/general
      - ${APP_DATA_DIR}/data/db:/database
    labels:
      generated: true
      traefik.enable: true
      traefik.http.middlewares.filebrowser-web-redirect.redirectscheme.scheme: https
      traefik.http.services.filebrowser.loadbalancer.server.port: "80"
      traefik.http.routers.filebrowser-local-insecure.rule: Host(`filebrowser.${LOCAL_DOMAIN}`)
      traefik.http.routers.filebrowser-local-insecure.entrypoints: web
      traefik.http.routers.filebrowser-local-insecure.service: filebrowser
      traefik.http.routers.filebrowser-local-insecure.middlewares: filebrowser-web-redirect
      traefik.http.routers.filebrowser-local.rule: Host(`filebrowser.${LOCAL_DOMAIN}`)
      traefik.http.routers.filebrowser-local.entrypoints: websecure
      traefik.http.routers.filebrowser-local.service: filebrowser
      traefik.http.routers.filebrowser-local.tls: true
      runtipi.managed: true
networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

